blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
        path('', posts_list, name='post_list'),
        path('tag/<slug:tag_slug>', posts_list, name='post_list_by_tag'),
        # path('', PostsList.as_view(), name='post_list'),
        path('p/<slug:slug>/<int:year>/<int:month>/<int:day>/', post_details, name='post_details'),
        path('p/share/<int:post_id>/', share_post, name='share_post'),
        path('search/', search_posts, name='search_posts'),
]

djangobyexample/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from email.policy import default
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager

# Creating custom model manager to retreive all published posts in the db
class PublishedManager(models.Manager):
        def get_queryset(self):
            return super(PublishedManager, self).get_queryset().filter(status='published')
        

# Create your models here.
class Post(models.Model):
        STATUS_CHOICES  = (
                ('draft', 'Draft'),
                ('published', 'Published'),
        )
        title           = models.CharField("Title", max_length=50)
        slug            = models.SlugField(unique_for_date='publish', max_length=200)
        author          = models.ForeignKey(User, verbose_name="Author", on_delete=models.CASCADE, related_name='blog_post')
        body            = models.TextField()
        publish         = models.DateTimeField("Publish", default=timezone.now)
        created         = models.DateTimeField("Created", auto_now=True)
        updated         = models.DateTimeField("Updated", auto_now_add=True)
        status          = models.CharField("Status", max_length=10, default='draft', choices=STATUS_CHOICES)
        post_img        = models.ImageField(verbose_name="Post Image", upload_to='post_images/%y/%m/%d', max_length=200, default="post_images/default.jpg", blank=True, null=True)

        tags = TaggableManager()

        # model manager
        objects         = models.Manager() # the default model manager
        published_only  = PublishedManager() # my custom model manager added to it 

        class Meta:
                ordering = ('-publish',)
        
        def __str__(self):
            return self.title

        def get_absolute_url(self):
            return reverse('blog:post_details', kwargs={
                'slug':self.slug,
                'year':self.publish.year,
                'month':self.publish.month,
                'day':self.publish.day,
            })
        

class Comment(models.Model):
    post        = models.ForeignKey(Post, related_name="commentx", on_delete=models.CASCADE)
    name        = models.CharField("name", max_length=50)
    email       = models.EmailField('Email', max_length=254)
    body        = models.TextField()
    created     = models.DateTimeField(auto_now_add=True)
    updated     = models.DateTimeField(auto_now=True)
    active      = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return 'Comment by ' + self.name + ' on ' + self.post.title

    

blog/forms.py
from django import forms
from .models import Comment

class SharePostViaEmail(forms.Form):
        name            = forms.CharField(max_length=30)
        email           = forms.EmailField(max_length=50)
        to              = forms.EmailField(max_length=50)
        comments        = forms.CharField(
                                        required=False,
                                        widget=forms.Textarea
                                        )

class CommentForm(forms.ModelForm):
    class Meta:
        model   = Comment
        fields  = ("name", "email", "body")
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Name'}),
            'email': forms.TextInput(attrs={'placeholder': 'Email'}),
            'body': forms.Textarea(
                attrs={'placeholder': 'Comment'}),
        }

blog/views.py
from turtle import pos
from django.views.generic import ListView
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.mail import send_mail
from taggit.models import Tag
from django.db.models import Count, Q

from blog.forms import SharePostViaEmail, CommentForm
from .models import Post, Comment

# Create your views here.
# class PostsList(ListView):
#         queryset                = Post.published_only.all().order_by('publish')
#         context_object_name     = 'posts'
#         paginate_by             = 3
#         template_name           = 'blog/home.html'

def posts_list(request, tag_slug=None):
        context = {}
        
        _tag = None
        published_posts         = Post.published_only.all().order_by('-publish')
        alltags                 = Post.tags.all() 

        if tag_slug:
                _tag = get_object_or_404(
                        Tag,
                        slug=tag_slug,
                )
                published_posts         = Post.published_only.filter(tags__in=[_tag]).order_by('publish')

        paginator = Paginator(published_posts, 3) # 3 posts in each page

        page = request.GET.get('page')
        try:
                posts = paginator.page(page)
        except PageNotAnInteger:
                # If page is not an integer deliver the first page
                posts = paginator.page(1)
        except EmptyPage:
                # If page is out of range deliver last page of results
                posts = paginator.page(paginator.num_pages)

        context['posts']        = posts
        context['page']         = page
        context['tag']          = _tag
        context['tags']         = alltags
        
        return render(request, 'blog/home.html', context)

# Search function 
def search_posts(request):
	context = {}
	try:
		query   = request.GET['search']
		posts   = Post.published_only.filter(title__contains=query)
		alltags = Post.tags.all() 
		
		if posts:
			context['filtered_posts'] = posts
			context['query']          = query
			context['tags']         = alltags

			return render(request, 'blog/home.html', context)
		else :
			return redirect('blog:post_list')

	except KeyError:
		return redirect('blog:post_list')

# List post detail in one page 
def post_details(request, slug, year, month, day):
	context = {}

	post    = get_object_or_404(
		Post,
		slug            = slug,
		status          = 'published',
		publish__year   = year,
		publish__month  = month,
		publish__day    = day,
	)
	# List of active comments for this post | commentx is the related_name argument in post field in the Comment Module
	comments        = post.commentx.filter(active=True)
	comment_add     = None 

	if request.method == "POST":
		form = CommentForm(request.POST)
		if form.is_valid():
				name    = form.cleaned_data['name']
				email   = form.cleaned_data['email']
				body    = form.cleaned_data['body']

				# Comment.objects.create(
				#         Post,
				#         name  = name,
				#         email = email,
				#         body  = body
				# )
				comment_add = form.save(commit=False)
				comment_add.post = post
				comment_add.save()
	else:
		form = CommentForm()

	post_tags_ids   = post.tags.values_list("id", flat=True)
	similar_posts   = Post.published_only.filter(tags__in=post_tags_ids).exclude(id=post.id)
	similar_posts   = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]
	
	context['post']                 = post
	context['form']                 = form
	context['comments']             = comments
	context['comment']              = comment_add
	context['similar_posts']        = similar_posts

	return render(request, 'blog/post/details.html', context)

# Share post by E-mail 
def share_post(request, post_id):
	context = {}

	post    = get_object_or_404(
				Post,
				id=post_id,
				status='published'
	)
	sent = False

	if request.method == 'POST':
		# Form was submitted
		form = SharePostViaEmail(request.POST)
		if form.is_valid():
		# Form fields are valid
				cd = form.cleaned_data
				post_url = request.build_absolute_uri( post.get_absolute_url() )
				subject         = f"{cd['name']} shared a post with you"
				message         = f"You can read about {post.title} at {post_url}"\
										f" {cd['name']}'s comments : {cd['comments']}"
				send_mail(subject, message, request.user.email,[ cd['to'] ])
				sent = True
	else:
		# If it is a get request
		form = SharePostViaEmail()
	
	context['post']  = post
	context['form']  = form
	context['sent']  = sent

	return render(request, 'blog/post/share.html', context)

blog/templates/blog/post/details.html
{% extends "base.html" %}
{% load static %}
{% block styles %}
        <!-- Added Styles -->
        <link rel="stylesheet" href="{% static 'blog/css/details.css' %}">
{% endblock styles %}

{% block title %} {{post.title}} {% endblock title %}

{% block content %}
 {% if post %}

  <div class="post">

    {% if post.post_img %}
    <div class="post-img">
      <img src="{{post.post_img.url}}">
    </div>
    {% endif %}

    <p class="date"><br>
      <span>By: </span> <span class="lighter">{{ post.author }}</span> <span>,at </span> <span class="lighter">{{ post.publish.date }}</span>
    </p><br>

    <h1 class="title">{{ post.title }}</h1>
    
    <div class="post-body">
      {{ post.body|safe }}
    </div>
    
    <p class="share-this-post">
      <a href="{% url 'blog:share_post' post.id %}">Share this post  <span class="iconify-inline" data-icon="logos:google-gmail" data-width="19"></span>
      </a>
    </p>
    
    <div class="similar">
      {% if similar_posts %}
        <h2>Similar posts</h2>
        {% for post in similar_posts %}
          <p>
            <a href="{{post.get_absolute_url}}">{{post.title}}</a>
          </p>
        {% endfor %}
      {% endif %}
    </div>

    <div class="comments">
      {% with comments.count as total_comments %}
        <h2>{{ total_comments }} Comment{{ total_comments|pluralize }}</h2>
      {% endwith %}
      {% for comment in comments %}
        <div class="comment">
          <p class="info">
            {{ comment.name }}
          </p>
          {{ comment.body|linebreaks }}
          <p class="comment-date">
            {{ comment.created.date }}
          </p>
        </div>
        {% empty %}
          <p>There are no comments yet.</p>
      {% endfor %}
    </div>

    <div class="comment-form">
      {% if comment_add %}
        <h2>Comment added succesfully !</h2>
      {% else %}

        <p class="post-cmnt">
          Post a Comment
        </p>
        <div class="form">
          <form action="" method="post">
            {% csrf_token %}
            {% for field in form %}
              <div class="input-block">
                {{field.error}}
                {{field}}
              </div>
            {% endfor %}
            <p><input type="submit" value="Comment"></p>
          </form>
        </div>
      {% endif %}
    </div>
    
  </div>
  
 {% endif %}
{% endblock %}

{% block scripts %}
  <script src="{% static 'blog/js/iconify.min.js' %}"></script>
{% endblock scripts %}

blog/templates/blog/post/share.html
{% extends "base.html" %}

{% block content %}
 {% if sent %}
    <div class="check-sent">
        <h2>E-mail Sent Succesfully !</h2>
        <p>"{{post.title}}" Has been sent to {{form.cleaned_data.to}} Succesfully.</p>
    </div>
 {% else %}
    <div class="send-form">
        <h1>Share " {{post.title}} " by E-mail</h1>

        <form action="" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="field-block">
                      {{field.error}}
                      {{field.label_tag}}  {{field}}
                    </div>
                {% endfor %}
                <input type="submit" value="Send e-mail">
        </form>
    </div>
 {% endif %}
{% endblock %}