blog/urls.py
from django.urls import path
from .views import *

app_name = 'blog'

urlpatterns = [
        path('', posts_list, name='post_list'),
        path('tag/<slug:tag_slug>', posts_list, name='post_list_by_tag'),
        # path('', PostsList.as_view(), name='post_list'),
        path('p/<slug:slug>/<int:year>/<int:month>/<int:day>/', post_details, name='post_details'),
        path('p/share/<int:post_id>/', share_post, name='share_post'),
        path('search/', search_posts, name='search_posts'),
]

djangobyexample/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="{% static 'blog/css/style.css' %}">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
        {% block styles %}      {% endblock styles %}
        <title>{% block title %}{% endblock title %}</title>
</head>
<body>
<div class="container">

   <nav>
      <a id="header" href="{% url 'blog:post_list' %}"> <h1 class="header">DBlogo <i class="fa-solid fa-user-pen"></i></h1></a>
      <div class="nav-list">
         <ul>
            <li class="active"><a href="{% url 'blog:post_list' %}">Home</a></li>
            <li><a href="https://github.com/black15" target="_blank">Contact</a></li>
            <li>
               <div class="dropdown">
                  <i class="fa-solid fa-user-astronaut"></i>
                  <div class="dropdown-menu">
                     <a href="">New Blog <i class="fa-solid fa-plus"></i></a>
                     <a href="">Profile <i class="fa-solid fa-user"></i></a>
                  </div>
               </div>
            </li>
         </ul>
      </div>
   </nav>

   {% block content %}{% endblock content %}

</div>
</body>
        {% block scripts %}{% endblock scripts %}
</html>